### ISSUE TITLE
Can't parse CRD

### ISSUE THREAD

**Issue by Tchoupinax** [sl1pm4t/k2tf#108]
Hello,

I tried your project to parse an IngressRoute, that is a CRD provided by Traefik.

```
8:46PM Warn | could not parse file                                          error="2 errors occurred:\n\t* could not decode yaml object with main scheme #1: no kind \"IngressRoute\" is registered for version \"traefik.containo.us/v1alpha1\" in scheme \"pkg/runtime/scheme.go:100\"\n\t* could not decode yaml object with aggregator scheme #1: no kind \"IngressRoute\" is registered for version \"traefik.containo.us/v1alpha1\" in scheme \"pkg/runtime/scheme.go:100\"\n\n"
```

The file

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.localhost`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
```
And the command used is the following
```
k2tf -f ok.yml -o df.tf
```

Hope it will help you to improve your tool!

Have a nice day
