### ISSUE TITLE
stringData in a Kubernetes secret is not parsed

### ISSUE THREAD

**Issue by danielsteman** [sl1pm4t/k2tf#109]
I tried converting the following Kubernetes secret in yaml:

```
---
apiVersion: v1
kind: Secret
metadata:
  name: someSecretName
  namespace: someNamespace
type: Opaque
stringData:
  ACCOUNT: someAccount
  KEY: someKey
```

which is converted to:

```
resource "kubernetes_secret" "seldon_rclone_models_secret" {
  metadata {
    name      = "someSecretName"
    namespace = "someNamespace"
  }

  string_datum {}

  type = "Opaque"
}
```

It looks like stringData is not parsed. `string_data` is also not available in the Terraform api so it kinda makes sense. I'm still unsure to which argument it should map, since there is only `data` and `binary_data` as you can see [here](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/secret)
