### ISSUE TITLE
Feature: Support for salted secrets

### ISSUE THREAD

**Issue by henobi** [sl1pm4t/k2tf#114]
Support the conversion of SealedSecrets.

```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: mynamespace
spec:
  encryptedData:
    foo: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq.....

```
