### ISSUE TITLE
Can't convert ValidatingWebhookConfiguration

### ISSUE THREAD

**Issue by JordanP** [sl1pm4t/k2tf#134]
Hi,
Thanks for the wonderful program !

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: cnpg-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: cnpg-webhook-service
      namespace: cnpg-system
      path: /validate-postgresql-cnpg-io-v1-backup
  failurePolicy: Fail
  name: vbackup.cnpg.io
  rules:
  - apiGroups:
    - postgresql.cnpg.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backups
  sideEffects: None
```
gives
```hcl
resource "kubernetes_validating_webhook_configuration" "cnpg_validating_webhook_configuration" {
  metadata {
    name = "cnpg-validating-webhook-configuration"
  }
  webhook {
    name = "vbackup.cnpg.io"
    client_config {
      service {
        namespace = "cnpg-system"
        name      = "cnpg-webhook-service"
        path      = "/validate-postgresql-cnpg-io-v1-backup"
      }
    }
    rule {
      operations = ["CREATE", "UPDATE"]
    }
    failure_policy            = "Fail"
    side_effects              = "None"
    admission_review_versions = ["v1"]
  }
}
```

For some reason, the `rule` block is incomplete.
