### ISSUE TITLE
Warn excluding attribute - not found in Terraform schema   

### ISSUE THREAD

**Issue by zioproto** [sl1pm4t/k2tf#19]
This example yaml file will generate a false positive warning:
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    certmanager.k8s.io/disable-validation: "true"
```
How to reproduce:
```
cat 05-cert-manager.yaml | ./k2tf
10:12PM Warn | excluding attribute - not found in Terraform schema           attr=kubernetes_namespace.spec field=Namespace.Spec name=cert_manager type=kubernetes_namespace
resource "kubernetes_namespace" "cert_manager" {
  metadata {
    name = "cert-manager"

    labels {
      "certmanager.k8s.io/disable-validation" = "true"
    }
  }
}
```

The translation looks correct, I dont understand if the warning is a false positive.

Removing the line `kind: Namespace` fixes the warning.
