### ISSUE TITLE
Empty data fields are stripped from result

### ISSUE THREAD

**Issue by kim0** [sl1pm4t/k2tf#29]
When converting this

```
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard-csrf
  namespace: kubernetes-dashboard
type: Opaque
data:
  csrf: ""
```

The result does not contain the data.csrf field, while it should exist and be an empty value.
