### ISSUE TITLE
storageClass.parameters & provisioner are not converted

### ISSUE THREAD

**Issue by hdhruna** [sl1pm4t/k2tf#43]
I found an issue with version 0.2.8

An example storageClass:
```YAML
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: none
```
Command used to convert yaml2tf:
` k2tf -x -f manifests/yamls/test.yaml -o manifests/k8s/test.tf`

Converted tf object:
```hcl
resource "kubernetes_storage_class" "slow" {
  metadata {
    name = "slow"
  }

  parameter {}
}
```
It seems parameter & provisioner is missing out the arguments.
