### ISSUE TITLE
Default values for terraform and kubectl can be different

### ISSUE THREAD

**Issue by charlottemach** [sl1pm4t/k2tf#44]
When converting a daemonset.yaml without explicitly setting automount_service_account_token to true (which is the kubectl default), terraform puts false as a default. 

E.g. turning daemonset.yaml
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
[...]
spec:
  template:
    spec:
[...]
```
into terraform: 
```
resource "kubernetes_daemonset" "name" {
  metadata {
   [...]
  }
  spec {
    selector {
      match_labels = {
        [...]
      }
    }
    template {
      spec {
       [...]
```
results in:
```
apiVersion: apps/v1beta1
  kind: DaemonSet
  metadata:
    [...]
  spec:
    template:
      spec:
        automountServiceAccountToken: false
```
A specific example [can be found here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-EKS-quickstart.html), when trying to use k2tf on the quickstart.yaml, it needs the automountServiceAccountToken to be explicitly set to true, otherwise the services can't connect.
