### ISSUE TITLE
Fail to convert CRD yamls

### ISSUE THREAD

**Issue by bykvaadm** [sl1pm4t/k2tf#46]
4:13PM Fatal | %!s(<nil>)  error="2 errors occurred:\n\t* could not decode yaml object with main scheme #1: no kind \"CustomResourceDefinition\" is registered for version \"apiextensions.k8s.io/v1beta1\" in scheme \"pkg/runtime/scheme.go:101\"\n\t* could not decode yaml object with aggregator scheme #1: no kind \"CustomResourceDefinition\" is registered for version \"apiextensions.k8s.io/v1beta1\" in scheme \"pkg/runtime/scheme.go:101\"\n\n"

i.e.

```
kind: CustomResourceDefinition
metadata:
  name: clusterissuers.certmanager.k8s.io
  labels:
    app: cert-manager
spec:
  group: certmanager.k8s.io
  version: v1alpha1
  names:
    kind: ClusterIssuer
    plural: clusterissuers
  scope: Cluster
```
