### ISSUE TITLE
`ValidatingWebhookConfiguration` - webhook rules incorrectly translated

### ISSUE THREAD

**Issue by LightAndLight** [sl1pm4t/k2tf#72]
I ran `k2tf` on this document https://raw.githubusercontent.com/kubernetes/ingress-nginx/ingress-nginx-2.11.3/deploy/static/provider/cloud/deploy.yaml, which contains this resource definition:

```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    helm.sh/chart: ingress-nginx-2.11.1
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: 0.34.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: admission-webhook
  name: ingress-nginx-admission
webhooks:
  - name: validate.nginx.ingress.kubernetes.io
    rules:
      - apiGroups:
          - extensions
          - networking.k8s.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - ingresses
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        namespace: ingress-nginx
        name: ingress-nginx-controller-admission
        path: /extensions/v1beta1/ingresses
```

but the corresponding Terraform output looks like this:

```
resource "kubernetes_validating_webhook_configuration" "ingress_nginx_admission" {
  metadata {
    name = "ingress-nginx-admission"

    labels = {
      "app.kubernetes.io/component" = "admission-webhook"

      "app.kubernetes.io/instance" = "ingress-nginx"

      "app.kubernetes.io/managed-by" = "Helm"

      "app.kubernetes.io/name" = "ingress-nginx"

      "app.kubernetes.io/version" = "0.34.1"

      "helm.sh/chart" = "ingress-nginx-2.11.1"
    }
  }

  webhook {
    name = "validate.nginx.ingress.kubernetes.io"

    client_config {
      service {
        namespace = "ingress-nginx"
        name      = "ingress-nginx-controller-admission"
        path      = "/extensions/v1beta1/ingresses"
      }
    }

    rule {
      operations = ["CREATE", "UPDATE"]
    }

    failure_policy            = "Fail"
    side_effects              = "None"
    admission_review_versions = ["v1", "v1beta1"]
  }
}
```

The `apiGroups`, `apiVersions`, and `resources` are not translated, but they are required fields which means this is an invalid Terraform configuration.

**Comment by sl1pm4t** [comment]
Could you run k2tf with the --debug flag to see if it logs warnings about these fields.
I suspect it's probably not guessing the correct Terraform attribute name and then skipping because it's not found in the Terraform schema.

**Comment by LightAndLight** [comment]
Only `Debug` level logs are produced. There weren't any warnings.

**Comment by yuriy-yarosh** [comment]
Having the same issue while translating the Vault helm chart - [injector-mutating-webhook.yaml](https://github.com/hashicorp/vault-helm/blob/main/templates/injector-mutating-webhook.yaml) loses `apiGroups`, `apiVersions` and `resources` during translation.

**Comment by yuriy-yarosh** [comment]
```yaml
objectSelector:
  matchExpressions:
    - key: app.kubernetes.io/name
  operator: NotIn
  values:
    - injector
```

also gets translated to 

```hcl
object_selector {
  match_expressions {
    key      = component
    operator = "NotIn"
    values   = ["injector"]
  }
}
```
